/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.29.0
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

export type { VrfImplAbi } from './VrfImplAbi';

export { VrfImplAbi__factory } from './factories/VrfImplAbi__factory';
