/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.29.0
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

import type { Option, Enum } from "./common";

export type ErrorInput = Enum<{ ContractNotConfigured: [], AssetNotConfigured: [], NotAuthorized: [], RemainingAssets: [], NonZeroFee: [], ZeroAuthority: [], ZeroFee: [], NoFeePaid: [], WrongFeePaid: [], SeedInUse: [], NoAmountSpecified: [], NotEnoughFunds: [], UnknownRequest: [], InvalidResponse: [], Fulfilled: [] }>;
export type ErrorOutput = ErrorInput;
export type EventInput = Enum<{ Fulfill: FulfillInput, Response: ResponseInput, Request: RequestInput, Reset: ResetInput }>;
export type EventOutput = Enum<{ Fulfill: FulfillOutput, Response: ResponseOutput, Request: RequestOutput, Reset: ResetOutput }>;
export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export type RandomnessStateInput = Enum<{ Unfulfilled: UnfulfilledInput, Fulfilled: FulfilledInput }>;
export type RandomnessStateOutput = Enum<{ Unfulfilled: UnfulfilledOutput, Fulfilled: FulfilledOutput }>;

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;
export type B512Input = { bytes: [string, string] };
export type B512Output = B512Input;
export type ContractIdInput = { value: string };
export type ContractIdOutput = ContractIdInput;
export type FulfillInput = { seed: string, randomness: B512Input };
export type FulfillOutput = { seed: string, randomness: B512Output };
export type FulfilledInput = { randomness: B512Input, keys: FulfillersKeysInput };
export type FulfilledOutput = { randomness: B512Output, keys: FulfillersKeysOutput };
export type FulfillersKeysInput = { key1: AddressInput, key2: AddressInput, key3: AddressInput, key4: AddressInput, key5: AddressInput, key6: AddressInput, key7: AddressInput };
export type FulfillersKeysOutput = { key1: AddressOutput, key2: AddressOutput, key3: AddressOutput, key4: AddressOutput, key5: AddressOutput, key6: AddressOutput, key7: AddressOutput };
export type RandomnessInput = { seed: string, state: RandomnessStateInput };
export type RandomnessOutput = { seed: string, state: RandomnessStateOutput };
export type RequestInput = { seed: string, client: IdentityInput, no: BigNumberish };
export type RequestOutput = { seed: string, client: IdentityOutput, no: BN };
export type ResetInput = { seed: string };
export type ResetOutput = ResetInput;
export type ResponseInput = { seed: string, authority: AddressInput, randomness: B512Input };
export type ResponseOutput = { seed: string, authority: AddressOutput, randomness: B512Output };
export type UnfulfilledInput = { randomness: B512Input, keys: FulfillersKeysInput };
export type UnfulfilledOutput = { randomness: B512Output, keys: FulfillersKeysOutput };

interface VrfImplAbiInterface extends Interface {
  functions: {
    configure: FunctionFragment;
    configure_asset: FunctionFragment;
    fulfill: FunctionFragment;
    get_asset: FunctionFragment;
    get_authority: FunctionFragment;
    get_balance: FunctionFragment;
    get_fee: FunctionFragment;
    get_fulfillment_authorities: FunctionFragment;
    get_num_requests: FunctionFragment;
    get_request_by_num: FunctionFragment;
    get_request_by_seed: FunctionFragment;
    get_requests: FunctionFragment;
    request: FunctionFragment;
    withdraw_fees: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'configure', values: [IdentityInput, BigNumberish, [Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>]]): Uint8Array;
  encodeFunctionData(functionFragment: 'configure_asset', values: [ContractIdInput, BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'fulfill', values: [string, B512Input]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_asset', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_authority', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_balance', values: [ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_fee', values: [ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_fulfillment_authorities', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_num_requests', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_request_by_num', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_request_by_seed', values: [string]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_requests', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'request', values: [string]): Uint8Array;
  encodeFunctionData(functionFragment: 'withdraw_fees', values: [ContractIdInput, BigNumberish, AddressInput]): Uint8Array;

  decodeFunctionData(functionFragment: 'configure', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'configure_asset', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'fulfill', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_asset', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_authority', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_balance', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_fee', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_fulfillment_authorities', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_num_requests', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_request_by_num', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_request_by_seed', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_requests', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'request', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'withdraw_fees', data: BytesLike): DecodedValue;
}

export class VrfImplAbi extends Contract {
  interface: VrfImplAbiInterface;
  functions: {
    configure: InvokeFunction<[authority: IdentityInput, fee: BigNumberish, fulfillment_authorities: [Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>, Option<AddressInput>]], void>;
    configure_asset: InvokeFunction<[asset: ContractIdInput, fee: BigNumberish], void>;
    fulfill: InvokeFunction<[seed: string, signature: B512Input], void>;
    get_asset: InvokeFunction<[], ContractIdOutput>;
    get_authority: InvokeFunction<[], IdentityOutput>;
    get_balance: InvokeFunction<[asset: ContractIdInput], BN>;
    get_fee: InvokeFunction<[asset: ContractIdInput], BN>;
    get_fulfillment_authorities: InvokeFunction<[], [Option<AddressOutput>, Option<AddressOutput>, Option<AddressOutput>, Option<AddressOutput>, Option<AddressOutput>, Option<AddressOutput>, Option<AddressOutput>, Option<AddressOutput>, Option<AddressOutput>, Option<AddressOutput>]>;
    get_num_requests: InvokeFunction<[], BN>;
    get_request_by_num: InvokeFunction<[num: BigNumberish], Option<RandomnessOutput>>;
    get_request_by_seed: InvokeFunction<[seed: string], Option<RandomnessOutput>>;
    get_requests: InvokeFunction<[offset: BigNumberish], [Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>, Option<RandomnessOutput>]>;
    request: InvokeFunction<[seed: string], BN>;
    withdraw_fees: InvokeFunction<[asset: ContractIdInput, amount: BigNumberish, recipient_address: AddressInput], void>;
  };
}
