/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

import { Interface, Contract, ContractFactory } from "fuels";
import type { Provider, Account, AbstractAddress, BytesLike, DeployContractOptions, StorageSlot } from "fuels";
import type { VrfImplAbi, VrfImplAbiInterface } from "../VrfImplAbi";

const _abi = {
  "encoding": "1",
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "[_; 2]",
      "components": [
        {
          "name": "__array_element",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "[_; 7]",
      "components": [
        {
          "name": "__array_element",
          "type": 15,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "enum AccessError",
      "components": [
        {
          "name": "NotOwner",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "enum Error",
      "components": [
        {
          "name": "ContractNotConfigured",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "AssetNotConfigured",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotAuthorized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "RemainingAssets",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NonZeroFee",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "ZeroAuthority",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "ZeroFee",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NoFeePaid",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "WrongFeePaid",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "SeedInUse",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NoAmountSpecified",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotEnoughFunds",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "UnknownRequest",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "InvalidResponse",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Responded",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Fulfilled",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 6,
      "type": "enum Event",
      "components": [
        {
          "name": "Fulfill",
          "type": 19,
          "typeArguments": null
        },
        {
          "name": "Response",
          "type": 28,
          "typeArguments": null
        },
        {
          "name": "Request",
          "type": 26,
          "typeArguments": null
        },
        {
          "name": "Reset",
          "type": 27,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 7,
      "type": "enum Identity",
      "components": [
        {
          "name": "Address",
          "type": 15,
          "typeArguments": null
        },
        {
          "name": "ContractId",
          "type": 18,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 8,
      "type": "enum InitializationError",
      "components": [
        {
          "name": "CannotReinitialized",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 9,
      "type": "enum Option",
      "components": [
        {
          "name": "None",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Some",
          "type": 12,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        12
      ]
    },
    {
      "typeId": 10,
      "type": "enum RandomnessState",
      "components": [
        {
          "name": "Unfulfilled",
          "type": 29,
          "typeArguments": null
        },
        {
          "name": "Fulfilled",
          "type": 20,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 11,
      "type": "enum State",
      "components": [
        {
          "name": "Uninitialized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Initialized",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "Revoked",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 12,
      "type": "generic T",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 13,
      "type": "raw untyped ptr",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 14,
      "type": "str",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 15,
      "type": "struct Address",
      "components": [
        {
          "name": "bits",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 16,
      "type": "struct AssetId",
      "components": [
        {
          "name": "bits",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 17,
      "type": "struct B512",
      "components": [
        {
          "name": "bits",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 18,
      "type": "struct ContractId",
      "components": [
        {
          "name": "bits",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 19,
      "type": "struct Fulfill",
      "components": [
        {
          "name": "seed",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "randomness",
          "type": 17,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 20,
      "type": "struct Fulfilled",
      "components": [
        {
          "name": "randomness",
          "type": 17,
          "typeArguments": null
        },
        {
          "name": "keys",
          "type": 21,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 21,
      "type": "struct FulfillersKeys",
      "components": [
        {
          "name": "keys",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 22,
      "type": "struct OwnershipSet",
      "components": [
        {
          "name": "new_owner",
          "type": 7,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 23,
      "type": "struct OwnershipTransferred",
      "components": [
        {
          "name": "new_owner",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "previous_owner",
          "type": 7,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 24,
      "type": "struct Randomness",
      "components": [
        {
          "name": "seed",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "state",
          "type": 10,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 25,
      "type": "struct RawVec",
      "components": [
        {
          "name": "ptr",
          "type": 13,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 31,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        12
      ]
    },
    {
      "typeId": 26,
      "type": "struct Request",
      "components": [
        {
          "name": "seed",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "client",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "no",
          "type": 31,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 27,
      "type": "struct Reset",
      "components": [
        {
          "name": "seed",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 28,
      "type": "struct Response",
      "components": [
        {
          "name": "seed",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "authority",
          "type": 15,
          "typeArguments": null
        },
        {
          "name": "randomness",
          "type": 17,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 29,
      "type": "struct Unfulfilled",
      "components": [
        {
          "name": "randomness",
          "type": 17,
          "typeArguments": null
        },
        {
          "name": "keys",
          "type": 21,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 30,
      "type": "struct Vec",
      "components": [
        {
          "name": "buf",
          "type": 25,
          "typeArguments": [
            {
              "name": "",
              "type": 12,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "len",
          "type": 31,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        12
      ]
    },
    {
      "typeId": 31,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [],
      "name": "owner",
      "output": {
        "name": "",
        "type": 11,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "authority",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "fee",
          "type": 31,
          "typeArguments": null
        },
        {
          "name": "fulfillment_authorities",
          "type": 30,
          "typeArguments": [
            {
              "name": "",
              "type": 15,
              "typeArguments": null
            }
          ]
        }
      ],
      "name": "configure",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset",
          "type": 16,
          "typeArguments": null
        },
        {
          "name": "fee",
          "type": 31,
          "typeArguments": null
        }
      ],
      "name": "configure_asset",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "seed",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "signature",
          "type": 17,
          "typeArguments": null
        }
      ],
      "name": "fulfill",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_asset",
      "output": {
        "name": "",
        "type": 16,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset",
          "type": 16,
          "typeArguments": null
        }
      ],
      "name": "get_balance",
      "output": {
        "name": "",
        "type": 31,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset",
          "type": 16,
          "typeArguments": null
        }
      ],
      "name": "get_fee",
      "output": {
        "name": "",
        "type": 31,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_fulfillment_authorities",
      "output": {
        "name": "",
        "type": 30,
        "typeArguments": [
          {
            "name": "",
            "type": 15,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_num_requests",
      "output": {
        "name": "",
        "type": 31,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "num",
          "type": 31,
          "typeArguments": null
        }
      ],
      "name": "get_request_by_num",
      "output": {
        "name": "",
        "type": 9,
        "typeArguments": [
          {
            "name": "",
            "type": 24,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "seed",
          "type": 3,
          "typeArguments": null
        }
      ],
      "name": "get_request_by_seed",
      "output": {
        "name": "",
        "type": 9,
        "typeArguments": [
          {
            "name": "",
            "type": 24,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "offset",
          "type": 31,
          "typeArguments": null
        }
      ],
      "name": "get_requests",
      "output": {
        "name": "",
        "type": 30,
        "typeArguments": [
          {
            "name": "",
            "type": 24,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "seed",
          "type": 3,
          "typeArguments": null
        }
      ],
      "name": "request",
      "output": {
        "name": "",
        "type": 31,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset",
          "type": 16,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 31,
          "typeArguments": null
        },
        {
          "name": "recipient_address",
          "type": 15,
          "typeArguments": null
        }
      ],
      "name": "withdraw_fees",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "11005223066266839355",
      "loggedType": {
        "name": "",
        "type": 5,
        "typeArguments": []
      }
    },
    {
      "logId": "2161305517876418151",
      "loggedType": {
        "name": "",
        "type": 8,
        "typeArguments": []
      }
    },
    {
      "logId": "16280289466020123285",
      "loggedType": {
        "name": "",
        "type": 22,
        "typeArguments": []
      }
    },
    {
      "logId": "4571204900286667806",
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": "12970362301975156672",
      "loggedType": {
        "name": "",
        "type": 23,
        "typeArguments": []
      }
    },
    {
      "logId": "10098701174489624218",
      "loggedType": {
        "name": "",
        "type": 14,
        "typeArguments": null
      }
    },
    {
      "logId": "16546776185816187435",
      "loggedType": {
        "name": "",
        "type": 6,
        "typeArguments": []
      }
    }
  ],
  "messagesTypes": [],
  "configurables": []
};

const _storageSlots: StorageSlot[] = [
  {
    "key": "94b2b70d20da552763c7614981b2a4d984380d7ed4e54c01b28c914e79e44bd5",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "de9090cb50e71c2588c773487d1da7066d0c719849a7e58dc8b6397a25c567c0",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "de9090cb50e71c2588c773487d1da7066d0c719849a7e58dc8b6397a25c567c1",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export const VrfImplAbi__factory = {
  abi: _abi,

  storageSlots: _storageSlots,

  createInterface(): VrfImplAbiInterface {
    return new Interface(_abi) as unknown as VrfImplAbiInterface
  },

  connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): VrfImplAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as VrfImplAbi
  },

  async deployContract(
    bytecode: BytesLike,
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<VrfImplAbi> {
    const factory = new ContractFactory(bytecode, _abi, wallet);

    const contract = await factory.deployContract({
      storageSlots: _storageSlots,
      ...options,
    });

    return contract as unknown as VrfImplAbi;
  }
}
