"use strict";
/* Autogenerated file. Do not edit manually. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VrfImplAbi__factory = void 0;
var VrfImplAbi__factory_1 = require("./factories/VrfImplAbi__factory");
Object.defineProperty(exports, "VrfImplAbi__factory", { enumerable: true, get: function () { return VrfImplAbi__factory_1.VrfImplAbi__factory; } });
