[project]
authors = ["ORAO Network Developers <hello@orao.network>"]
entry = "main.sw"
license = "Apache-2.0"
name = "russian-roulette"

[dependencies]
vrf_abi = { path = "../../../abi" }
std = { git = "https://github.com/FuelLabs/sway", tag = "v0.49.3" }